sudo: required
dist: trusty

language: cpp

cache:
  directories:
    - $HOME/travisCacheDir

env:
  global:
    # GitHub auth token (GH_AUTH_TOKEN)
    - secure: "1QBbD9VXAx3Mn0vFmHZtm6/sq+twMyR7ilQh7TQm8gBy2TrjhHKDKQ4wRQ5sa2MUFUbzrUOvPlPGq1WuY1mAUt8UE6jZDJNyyDWb6iIlcEmNRsd39XAhYHvJ+uI9JsD+U3OctZ+7Bo4fno0RLv1D5lzh5bpohmjgWxx9TiSZItbsRU+m0XM0Tahx335aXF8NFoVjheGXCOcLAXDt6OmaKPmlrXreuta5nOoRKeOg5vHlt/KNU1pYb8MFvWJc14DKxq3jNqrYlo9vHFv5tVhR1aqvVFWTD/4Z88OSxx3POzyVWdMso0lFov9uxs8qHoqLsGhDMElggyz/jnqZIHpwQMaYIGQ0LLYDv21jGgOuCOWKYlfjDY+tuESXmVPzerTlYBWLZDPrpE8BnXVYo8B/sF4WN6oCuBRjawlqYhqTH+tDDORc9Uc9pamhcuh6OsLMx3PHoyg8joN3t8yUnwhySXyfQ36hqlZ+Y4bBDRZBH/SB/EPmedyLGwdhzQFsUnOBotYeOym7LUdnGraGcj1iTPLdo5TMlBYlAiB12J5mHTNuzUKXh+PBV4REg4Mm2xYX+Pue5Qo1JcOWJteIX4BdPv526DXB3yaNWS1pZgGvYqtBwQlCeOfwOYupS0PksvmV7aX7c4qJSyW3dmEd03cxmebD0b2SbqyPxGFuUajJ7B60="
  matrix:
   - BUILD_VERSION=""
   - BUILD_VERSION="disable_autoupdate"
   - BUILD_VERSION="disable_register_custom_scheme"
   - BUILD_VERSION="disable_crash_reports"
   - BUILD_VERSION="disable_network_proxy"
   - BUILD_VERSION="disable_desktop_file_generation"
   - BUILD_VERSION="disable_unity_integration"

matrix:
  fast_finish: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - bison
      - build-essential
      - cmake
      - devscripts
      - dpatch
      - equivs
      - fakeroot
      - g++-4.9
      - gcc-4.9
      - git
      - gnome-common
      - gobject-introspection
      - gtk-doc-tools
      - libappindicator-dev
      - libasound2-dev
      - libdbusmenu-glib-dev
      - liblzma-dev
      - libopus-dev
      - libpulse-dev
      - libssl-dev
      - libunity-dev
      - libva-dev
      - libxcb-xkb-dev
      - libxkbcommon-dev
      - lintian
      - quilt
      - valac
      - xutils-dev
      - yasm

before_install:
  - "export TRAVIS_COMMIT_MSG=\"$(git log --format=%B --no-merges -n 1)\""
  - .travis/check.sh
  - export CXX="g++-4.9" CC="gcc-4.9"
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
  - sudo update-alternatives --config gcc
  - g++ --version

script:
  - .travis/build.sh
